version: '3.8'
services:
  autodubber:
    build: .
    container_name: autodubber
    restart: unless-stopped
    volumes:
      - ./config:/app/config:ro
      - ./logs:/app/logs
      - ./tmp:/tmp/autodubber
      - ./client_secrets.json:/app/client_secrets.json:ro
    environment:
      - TZ=UTC
      - PYTHONUNBUFFERED=1
      - LOG_LEVEL=INFO
    # Expose port for OAuth callback during initial auth
    ports:
      - "8080:8080"
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 1G